import os
import ast
from pathlib import Path
from collections import defaultdict

BACKEND_DIR = Path(r"c:\ess\ess_sample_2\backend\app")
ARTIFACTS_DIR = Path(r"C:\Users\dell\.gemini\antigravity-ide\brain\0093acac-024f-4ad3-8651-7c86d23f77d2")

def parse_python_file(filepath):
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read()
        tree = ast.parse(content)
        classes = {}
        for node in tree.body:
            if isinstance(node, ast.ClassDef):
                methods = [m.name for m in node.body if isinstance(m, ast.FunctionDef) or isinstance(m, ast.AsyncFunctionDef)]
                classes[node.name] = methods
        return classes
    except Exception as e:
        return {}

def analyze_codebase():
    report = "# Complete Project Codebase & Business Layer Report\n\n"
    report += "This report was generated by statically analyzing the AST of every Python file in the backend to document the actual implementation of the Business Layers.\n\n"

    if not BACKEND_DIR.exists():
        return "Backend directory not found."

    engines = [d for d in os.listdir(BACKEND_DIR) if (BACKEND_DIR / d).is_dir() and d not in ["scripts", "__pycache__", "core", "db", "scheduler"]]
    
    for engine in sorted(engines):
        engine_path = BACKEND_DIR / engine
        report += f"## Engine: `{engine.upper()}`\n\n"
        
        layers = ["models", "schemas", "repositories", "validators", "services", "controllers", "engine", "events"]
        
        for layer in layers:
            layer_path = engine_path / layer
            if not layer_path.exists():
                continue
                
            files = [f for f in os.listdir(layer_path) if f.endswith(".py") and f != "__init__.py"]
            if not files:
                continue
                
            report += f"### Layer: {layer.capitalize()}\n"
            for file in sorted(files):
                filepath = layer_path / file
                classes = parse_python_file(filepath)
                
                if not classes:
                    report += f"- `{file}`: *No classes detected (Utility or Route file)*\n"
                    continue
                
                for cls_name, methods in classes.items():
                    report += f"- **Class:** `{cls_name}` (File: `{file}`)\n"
                    if methods:
                        report += "  - **Methods:**\n"
                        for method in methods:
                            if method != "__init__":
                                report += f"    - `{method}()`\n"
            report += "\n"
            
        report += "---\n\n"

    return report

if __name__ == "__main__":
    report_content = analyze_codebase()
    output_path = ARTIFACTS_DIR / "project_codebase_analysis_report.md"
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(report_content)
    print("Codebase report generated successfully.")
