from fastapi import APIRouter
from .leave_policy_routes import router as leave_policy_router
from .leave_policy_version_routes import router as leave_policy_version_router
from .leave_policy_history_routes import router as leave_policy_history_router
from .leave_type_routes import router as leave_type_router
from .leave_eligibility_rule_routes import router as leave_eligibility_rule_router
from .leave_accrual_rule_routes import router as leave_accrual_rule_router
from .leave_carry_forward_rule_routes import router as leave_carry_forward_rule_router
from .leave_encashment_rule_routes import router as leave_encashment_rule_router
from .leave_restriction_rule_routes import router as leave_restriction_rule_router
from .leave_approval_workflow_routes import router as leave_approval_workflow_router
from .leave_holiday_rule_routes import router as leave_holiday_rule_router
from .leave_sandwich_rule_routes import router as leave_sandwich_rule_router
from .leave_negative_balance_rule_routes import router as leave_negative_balance_rule_router
from .leave_penalty_rule_routes import router as leave_penalty_rule_router
from .leave_quota_policy_routes import router as leave_quota_policy_router
from .leave_conversion_policy_routes import router as leave_conversion_policy_router
from .leave_year_configuration_routes import router as leave_year_configuration_router
from .workforce_availability_threshold_routes import router as workforce_availability_threshold_router
from .simulator_routes import router as simulator_router
\nleave_policy_router = APIRouter()
leave_policy_router.include_router(leave_policy_router)
leave_policy_router.include_router(leave_policy_version_router)
leave_policy_router.include_router(leave_policy_history_router)
leave_policy_router.include_router(leave_type_router)
leave_policy_router.include_router(leave_eligibility_rule_router)
leave_policy_router.include_router(leave_accrual_rule_router)
leave_policy_router.include_router(leave_carry_forward_rule_router)
leave_policy_router.include_router(leave_encashment_rule_router)
leave_policy_router.include_router(leave_restriction_rule_router)
leave_policy_router.include_router(leave_approval_workflow_router)
leave_policy_router.include_router(leave_holiday_rule_router)
leave_policy_router.include_router(leave_sandwich_rule_router)
leave_policy_router.include_router(leave_negative_balance_rule_router)
leave_policy_router.include_router(leave_penalty_rule_router)
leave_policy_router.include_router(leave_quota_policy_router)
leave_policy_router.include_router(leave_conversion_policy_router)
leave_policy_router.include_router(leave_year_configuration_router)
leave_policy_router.include_router(workforce_availability_threshold_router)
leave_policy_router.include_router(simulator_router)
