from fastapi import APIRouter
from app.employee.routes.employee_routes import router as emp_crud_router
from app.employee.routes.employee_personal_routes import router as employee_personal_router
from app.employee.routes.employee_contact_routes import router as employee_contact_router
from app.employee.routes.employee_address_routes import router as employee_address_router
from app.employee.routes.employee_bank_routes import router as employee_bank_router
from app.employee.routes.employee_emergency_contact_routes import router as employee_emergency_contact_router
from app.employee.routes.employee_family_routes import router as employee_family_router
from app.employee.routes.employee_education_routes import router as employee_education_router
from app.employee.routes.employee_experience_routes import router as employee_experience_router
from app.employee.routes.employee_document_routes import router as employee_document_router
from app.employee.routes.employment_history_routes import router as employment_history_router
from app.employee.routes.employee_shift_assignment_routes import router as employee_shift_assignment_router
from app.employee.routes.employee_role_assignment_routes import router as employee_role_assignment_router
from app.employee.routes.employee_reporting_routes import router as employee_reporting_router
from app.employee.routes.employee_probation_routes import router as employee_probation_router
from app.employee.routes.employee_confirmation_routes import router as employee_confirmation_router
from app.employee.routes.employee_exit_routes import router as employee_exit_routes
from app.employee.routes.employee_government_id_routes import router as employee_government_id_routes
from app.employee.routes.employee_payroll_config_routes import router as employee_payroll_config_routes

employee_router = APIRouter()
employee_router.include_router(emp_crud_router)
employee_router.include_router(employee_personal_router)
employee_router.include_router(employee_contact_router)
employee_router.include_router(employee_address_router)
employee_router.include_router(employee_bank_router)
employee_router.include_router(employee_emergency_contact_router)
employee_router.include_router(employee_family_router)
employee_router.include_router(employee_education_router)
employee_router.include_router(employee_experience_router)
employee_router.include_router(employee_document_router)
employee_router.include_router(employment_history_router)
employee_router.include_router(employee_shift_assignment_router)
employee_router.include_router(employee_role_assignment_router)
employee_router.include_router(employee_reporting_router)
employee_router.include_router(employee_probation_router)
employee_router.include_router(employee_confirmation_router)
employee_router.include_router(employee_exit_routes)
employee_router.include_router(employee_government_id_routes)
employee_router.include_router(employee_payroll_config_routes)
