from fastapi import APIRouter
from app.attendance_policy.routes.attendance_policy import router as my_attendance_policy_router
from app.attendance_policy.routes.weekly_off_policy import router as my_weekly_off_policy_router

attendance_policy_router = APIRouter()
attendance_policy_router.include_router(my_attendance_policy_router)
attendance_policy_router.include_router(my_weekly_off_policy_router)
