from fastapi import APIRouter
from app.leave.routes.leave_balance_routes import router as leave_balance_router
from app.leave.routes.leave_ledger_routes import router as leave_ledger_router
from app.leave.routes.leave_application_routes import router as leave_application_router
from app.leave.routes.leave_approval_routes import router as leave_approval_router
from app.leave.routes.leave_history_routes import router as leave_history_router
from app.leave.routes.leave_adjustment_routes import router as leave_adjustment_router
from app.leave.routes.leave_cancellation_routes import router as leave_cancellation_router
from app.leave.routes.leave_attachment_routes import router as leave_attachment_router
from app.leave.routes.leave_encashment_routes import router as leave_encashment_router
from app.leave.routes.comp_off_balance_routes import router as comp_off_balance_router
from app.leave.routes.comp_off_ledger_routes import router as comp_off_ledger_router
from app.leave.routes.leave_calendar_routes import router as leave_calendar_router
from app.leave.routes.leave_summary_routes import router as leave_summary_router
from app.leave.routes.attendance_penalty_ledger_processing_routes import router as attendance_penalty_ledger_processing_router
from app.leave.routes.leave_reservation_routes import router as leave_reservation_router
from app.leave.routes.leave_closing_routes import router as leave_closing_router
from app.leave.routes.dashboard_routes import router as dashboard_router
leave_router = APIRouter()
leave_router.include_router(leave_balance_router)
leave_router.include_router(leave_ledger_router)
leave_router.include_router(leave_application_router)
leave_router.include_router(leave_approval_router)
leave_router.include_router(leave_history_router)
leave_router.include_router(leave_adjustment_router)
leave_router.include_router(leave_cancellation_router)
leave_router.include_router(leave_attachment_router)
leave_router.include_router(leave_encashment_router)
leave_router.include_router(comp_off_balance_router)
leave_router.include_router(comp_off_ledger_router)
leave_router.include_router(leave_calendar_router)
leave_router.include_router(leave_summary_router)
leave_router.include_router(attendance_penalty_ledger_processing_router)
leave_router.include_router(leave_reservation_router)
leave_router.include_router(leave_closing_router)
leave_router.include_router(dashboard_router)
